import os
from typing import Annotated, TypedDict, Any
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.types import interrupt, Command
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.messages import BaseMessage, AIMessage, HumanMessage, ToolMessage
from langchain_core.tools import tool
from langchain_core.runnables import RunnableConfig


# ============================================================
# 1. 定义状态结构
# ============================================================
class State(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]


# ============================================================
# 2. 基础 Mock 工具（无中断，用于常规 Agent）
# ============================================================
@tool
def get_weather(location: str) -> str:
    """获取指定城市的天气信息。"""
    return f"【工具返回】{location}今天天气晴朗，温度为 68°F，东风 2 级，空气质量优。"


@tool
def search_movies(genre: str) -> str:
    """搜索并推荐指定类型的经典电影。"""
    return f"【工具返回】推荐以下经典{genre}电影：《星际穿越》、《沙丘》、《银翼杀手 2049》。"


@tool
def search_papers(query: str) -> str:
    """在学术文献库中检索学术论文。"""
    return f"【工具返回】为您检索到关于 '{query}' 的最新文献：\n1. 《Deep Graph Networks: A Survey》\n2. 《Agentic RAG with Memory Flow》\n3. 《Hierarchical LangGraph Workflows for Enterprises》"


@tool
def write_code(language: str, requirement: str) -> str:
    """根据需求编写指定编程语言的代码。"""
    lang = language.lower().strip()
    if "python" in lang or "py" in lang:
        code = (
            "```python\n"
            "def binary_search(arr, target):\n"
            "    # Requirement: " + requirement + "\n"
            "    low, high = 0, len(arr) - 1\n"
            "    while low <= high:\n"
            "        mid = (low + high) // 2\n"
            "        if arr[mid] == target:\n"
            "            return mid\n"
            "        elif arr[mid] < target:\n"
            "            low = mid + 1\n"
            "        else:\n"
            "            high = mid - 1\n"
            "    return -1\n"
            "```"
        )
    elif "java" in lang or "jvm" in lang:
        code = (
            "```java\n"
            "public class Solution {\n"
            "    // Requirement: " + requirement + "\n"
            "    public static void main(String[] args) {\n"
            "        System.out.println(\"Hello Code Agent!\");\n"
            "    }\n"
            "}\n"
            "```"
        )
    else:
        code = (
            "```javascript\n"
            "// Requirement: " + requirement + "\n"
            "function solve() {\n"
            "    console.log('Code generated by Code Agent');\n"
            "}\n"
            "```"
        )
    return f"【工具返回】已为您生成相关的 {language} 代码：\n\n{code}"


# ============================================================
# 3. HITL 工具：发送电子邮件（带中断审批）
#    对应 notebook 中 send_email / send_email_v2 的人机协同模式
# ============================================================
@tool
def send_email_hitl(to_address: str, subject: str, body: str) -> str:
    """给指定的电子邮箱发送邮件——此操作需要人工审批。"""

    # 暂停执行，等待人工审批（对应 notebook 的 interrupt 模式）
    response = interrupt({
        "type": "tool_approval",
        "tool_name": "send_email",
        "args": {
            "to_address": to_address,
            "subject": subject,
            "body": body,
        },
        "message": "请审核此邮件。您可以选择批准、拒绝或进行编辑。",
        "severity": "medium",
    })

    # 处理不同的响应类型（对应 notebook 的 approve / reject / edit 模式）
    if response.get("action") == "approve":
        return f"【工具返回】已成功向 <{to_address}> 发送主题为《{subject}》的邮件，内容大小：{len(body)} 字节。"

    elif response.get("action") == "reject":
        return "【工具返回】邮件发送已被用户取消。"

    elif response.get("action") == "edit":
        # 使用编辑后的新值
        to_address = response.get("to_address", to_address)
        subject = response.get("subject", subject)
        body = response.get("body", body)
        return (
            f"【工具返回】已使用编辑后的内容发送邮件：\n"
            f"收件人: {to_address}\n"
            f"主题: {subject}\n"
            f"正文: {body}"
        )

    return "【工具返回】未知的响应类型，操作已取消。"


# ============================================================
# 4. HITL 工具：删除数据库（高危险操作，双层安全机制）
#    对应 notebook 中 delete_database 示例
# ============================================================
@tool
def delete_database(database_name: str) -> str:
    """删除数据库。此操作极其危险！"""

    response = interrupt({
        "type": "tool_approval",
        "tool_name": "delete_database",
        "args": {
            "database_name": database_name,
        },
        "message": "你绝对确定要删除这个数据库吗？此操作不可撤销！",
        "severity": "high",
    })

    if response.get("action") == "approve":
        return f"【工具返回】数据库 '{database_name}' 已被删除（模拟操作）。"
    else:
        return "【工具返回】数据库删除操作已被取消。"


# ============================================================
# 5. HITL 工具：采购（金额阈值自动审批）
#    对应 notebook 课后练习：make_purchase 采购审批
# ============================================================
@tool
def make_purchase(item_name: str, amount: float) -> str:
    """进行采购。超过 $1000 的采购需要人工审批。"""

    if amount > 1000:
        # 大额采购需要审批
        response = interrupt({
            "type": "tool_approval",
            "tool_name": "make_purchase",
            "args": {
                "item_name": item_name,
                "amount": amount,
            },
            "message": f"采购金额 ${amount:.2f} 超过 $1000 阈值，需要人工审批。",
            "severity": "high",
            "reason": "amount_exceeds_threshold",
        })

        if response.get("action") == "approve":
            return f"【工具返回】已批准采购 {item_name}，金额 ${amount:.2f}。"
        elif response.get("action") == "reject":
            return f"【工具返回】采购 {item_name}（${amount:.2f}）已被拒绝。"
        else:
            return "【工具返回】采购操作已取消。"
    else:
        # 小额采购自动处理
        return f"【工具返回】已自动完成采购 {item_name}，金额 ${amount:.2f}。"


# ============================================================
# 6. 中间件 (Middleware) 类
#    对应 notebook 第三部分：AgentMiddleware 安全检测与日志
# ============================================================
class SafetyMiddleware:
    """
    安全中间件：在模型输出后检测危险工具调用并记录日志。
    对应 notebook 中的 SafetyMiddleware 模式。
    """

    name = "safety_checker"
    dangerous_keywords = ["delete", "destroy", "drop", "wipe"]

    def after_model(self, state: dict[str, Any], runtime=None) -> dict[str, Any] | None:
        """检查模型输出中是否包含危险工具调用。"""
        messages = state.get("messages", [])
        if not messages:
            return None

        last_message = messages[-1]
        tool_calls = getattr(last_message, "tool_calls", None) or []

        for tc in tool_calls:
            tool_name = tc.get("name", "").lower()
            for kw in self.dangerous_keywords:
                if kw in tool_name:
                    print(f"   [SAFETY] Dangerous operation detected!")
                    print(f"   Tool: {tc.get('name')}")
                    print(f"   Args: {tc.get('args')}")
        return None


class RequestLoggerMiddleware:
    """
    请求日志中间件：在模型调用前后打印调试信息。
    对应 notebook 中的 RequestLoggerMiddleware 模式。
    """

    name = "request_logger"

    def before_model(self, state: dict[str, Any], runtime=None) -> dict[str, Any] | None:
        message_count = len(state.get("messages", []))
        print(f"[BEFORE MODEL] Processing {message_count} messages")
        return None

    def after_model(self, state: dict[str, Any], runtime=None) -> dict[str, Any] | None:
        messages = state.get("messages", [])
        if messages:
            last = messages[-1]
            tool_calls = getattr(last, "tool_calls", None) or []
            if tool_calls:
                print(f"[AFTER MODEL] Model requested {len(tool_calls)} tool call(s)")
            else:
                print(f"[AFTER MODEL] Model provided final response")
        return None


# ============================================================
# 7. 工具注册表
# ============================================================
# 常规工具（无中断）
regular_tools = [get_weather, search_movies, search_papers, write_code]
tools_by_name = {tool.name: tool for tool in regular_tools}

# HITL 工具（含中断）
hitl_tools = [send_email_hitl, delete_database, make_purchase]
hitl_tools_by_name = {tool.name: tool for tool in hitl_tools}

# 全部工具
all_tools = regular_tools + hitl_tools


# ============================================================
# 8. 助手节点（LLM）—— Agent 路由逻辑
# ============================================================
def assistant(state: State, config: RunnableConfig = None):
    messages = state["messages"]
    last_message = messages[-1]

    # 如果最后一条是 ToolMessage，总结工具结果
    if isinstance(last_message, ToolMessage):
        reply = f"根据工具的查询结果，以下是为您整理的信息：\n\n{last_message.content}"
        return {"messages": [AIMessage(content=reply)]}

    content = last_message.content.lower() if last_message.content else ""

    assistant_id = "101 Weather Agent"
    if config and "configurable" in config:
        assistant_id = config["configurable"].get("assistant_id", "101 Weather Agent")

    # A. 101 Weather Agent
    if assistant_id == "101 Weather Agent":
        if any(k in content for k in ["weather", "天气", "旧金山", "sf"]):
            return {
                "messages": [
                    AIMessage(
                        content="",
                        tool_calls=[{
                            "name": "get_weather",
                            "args": {"location": "旧金山"},
                            "id": "call_weather_mock_id"
                        }]
                    )
                ]
            }
        reply = f"【101 天气助手】您好！您可以试着问我天气相关问题。"
        return {"messages": [AIMessage(content=reply)]}

    # B. Email Agent (HITL 版本)
    elif assistant_id == "Email Agent":
        if any(k in content for k in ["email", "邮件", "发送", "发信", "mail"]):
            return {
                "messages": [
                    AIMessage(
                        content="",
                        tool_calls=[{
                            "name": "send_email_hitl",
                            "args": {
                                "to_address": "manager@company.com",
                                "subject": "工作周报汇报",
                                "body": last_message.content
                            },
                            "id": "call_email_hitl_id"
                        }]
                    )
                ]
            }
        reply = f"【邮件助手】您可以尝试发送一封邮件给我。"
        return {"messages": [AIMessage(content=reply)]}

    # C. Research Agent
    elif assistant_id == "Research Agent":
        if any(k in content for k in ["research", "paper", "论文", "学术", "检索", "文献"]):
            return {
                "messages": [
                    AIMessage(
                        content="",
                        tool_calls=[{
                            "name": "search_papers",
                            "args": {"query": last_message.content},
                            "id": "call_research_mock_id"
                        }]
                    )
                ]
            }
        reply = f"【学术研究助手】您可以尝试检索学术论文。"
        return {"messages": [AIMessage(content=reply)]}

    # D. Deep Agent
    elif assistant_id == "Deep Agent":
        if any(k in content for k in ["movie", "电影", "科幻", "sci-fi"]):
            return {
                "messages": [
                    AIMessage(
                        content="",
                        tool_calls=[{
                            "name": "search_movies",
                            "args": {"genre": "科幻"},
                            "id": "call_movie_mock_id"
                        }]
                    )
                ]
            }
        reply = f"【深度思考智能体】我可以帮您搜索电影或回答复杂问题！"
        return {"messages": [AIMessage(content=reply)]}

    # E. Code Agent
    elif assistant_id == "Code Agent":
        if any(k in content for k in ["code", "代码", "编程", "写代码", "python", "java", "javascript", "js", "cpp", "c++"]):
            lang = "python"
            if "java" in content:
                lang = "java"
            elif "javascript" in content or "js" in content:
                lang = "javascript"
            elif "cpp" in content or "c++" in content:
                lang = "c++"
            return {
                "messages": [
                    AIMessage(
                        content="",
                        tool_calls=[{
                            "name": "write_code",
                            "args": {"language": lang, "requirement": last_message.content},
                            "id": "call_code_mock_id"
                        }]
                    )
                ]
            }
        reply = f"【代码生成助手】您可以试着让我写代码。"
        return {"messages": [AIMessage(content=reply)]}

    # F. Music Store Supervisor
    elif "supervisor" in assistant_id.lower():
        reply = f"【音乐商店监督员】已收到您的指示。"
        return {"messages": [AIMessage(content=reply)]}

    # G. HITL Agent (HITL Demo - 支持所有 HITL 工具)
    elif "hitl" in assistant_id.lower() or "approval" in assistant_id.lower():
        content_lower = content
        if any(k in content_lower for k in ["delete", "删除", "drop", "destroy"]):
            return {
                "messages": [
                    AIMessage(
                        content="",
                        tool_calls=[{
                            "name": "delete_database",
                            "args": {"database_name": "production_db"},
                            "id": "call_delete_hitl_id"
                        }]
                    )
                ]
            }
        elif any(k in content_lower for k in ["purchase", "采购", "buy", "购买"]):
            return {
                "messages": [
                    AIMessage(
                        content="",
                        tool_calls=[{
                            "name": "make_purchase",
                            "args": {"item_name": "Enterprise Server", "amount": 1500.0},
                            "id": "call_purchase_hitl_id"
                        }]
                    )
                ]
            }
        reply = f"【HITL 演示助手】我支持需要人工审批的操作。试试：'删除 production_db 数据库' 或 '采购一台企业服务器'。"
        return {"messages": [AIMessage(content=reply)]}

    # H. 默认
    reply = f"您好！我是智能体（{assistant_id}）。收到您的消息。"
    return {"messages": [AIMessage(content=reply)]}


# ============================================================
# 9. 工具节点
#    常规工具节点 vs HITL 工具节点
# ============================================================
def tool_node(state: State):
    """常规工具节点——直接执行工具，无中断。"""
    messages = state["messages"]
    last_message = messages[-1]

    tool_outputs = []
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        for tool_call in last_message.tool_calls:
            tool_name = tool_call["name"]
            tool_args = tool_call["args"]
            tool_func = tools_by_name.get(tool_name)
            if tool_func:
                res = tool_func.invoke(tool_args)
                tool_outputs.append(
                    ToolMessage(content=res, tool_call_id=tool_call["id"], name=tool_name)
                )

    return {"messages": tool_outputs}


def hitl_tool_node(state: State):
    """HITL 工具节点——执行带中断的工具。

    当工具内部调用 interrupt() 时，LangGraph 会引发 Interrupt 异常，
    图执行暂停并返回 __interrupt__ 信息。调用者通过 Command(resume=...) 恢复。
    """
    messages = state["messages"]
    last_message = messages[-1]

    tool_outputs = []
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        for tool_call in last_message.tool_calls:
            tool_name = tool_call["name"]
            tool_args = tool_call["args"]
            tool_func = hitl_tools_by_name.get(tool_name)
            if tool_func:
                res = tool_func.invoke(tool_args)
                tool_outputs.append(
                    ToolMessage(content=res, tool_call_id=tool_call["id"], name=tool_name)
                )

    return {"messages": tool_outputs}


# ============================================================
# 10. 条件路由
# ============================================================
def should_continue(state: State):
    messages = state["messages"]
    last_message = messages[-1]
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tool_node"
    return END


def should_continue_hitl(state: State):
    messages = state["messages"]
    last_message = messages[-1]
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "hitl_tool_node"
    return END


# ============================================================
# 11. 构建两个图：常规图 + HITL 图
# ============================================================

# --- 常规图（无中断）---
workflow = StateGraph(State)
workflow.add_node("assistant", assistant)
workflow.add_node("tool_node", tool_node)
workflow.add_edge(START, "assistant")
workflow.add_conditional_edges("assistant", should_continue, {
    "tool_node": "tool_node",
    END: END,
})
workflow.add_edge("tool_node", "assistant")

memory = MemorySaver()
graph = workflow.compile(checkpointer=memory, name="regular_graph")


# --- HITL 图（支持中断审批）---
hitl_workflow = StateGraph(State)
hitl_workflow.add_node("assistant", assistant)
hitl_workflow.add_node("hitl_tool_node", hitl_tool_node)
hitl_workflow.add_edge(START, "assistant")
hitl_workflow.add_conditional_edges("assistant", should_continue_hitl, {
    "hitl_tool_node": "hitl_tool_node",
    END: END,
})
hitl_workflow.add_edge("hitl_tool_node", "assistant")

hitl_memory = MemorySaver()
hitl_graph = hitl_workflow.compile(checkpointer=hitl_memory, name="hitl_graph")


# ============================================================
# 12. 工具元数据（供前端获取工具信息）
# ============================================================
def get_tools_meta():
    """返回所有工具的元数据，用于前端 HITL 审批表单生成。"""
    result = []
    for t in regular_tools + hitl_tools:
        result.append({
            "name": t.name,
            "description": t.description or "",
        })
    return result
