"""
所有工具函数和安全中间件。
- 常规工具（无中断）：天气、电影、论文、代码
- HITL 工具（含人工审批中断）：邮件、删除数据库、采购
- 中间件：安全检测、请求日志
"""

from typing import Any
from langgraph.types import interrupt
from langchain_core.tools import tool


# ============================================================
# 1. 常规 Mock 工具（无中断，用于常规 Agent）
# ============================================================
@tool
def get_weather(location: str) -> str:
    """获取指定城市的天气信息。"""
    return f"【工具返回】{location}今天天气晴朗，温度为 68°F，东风 2 级，空气质量优。"


@tool
def search_movies(genre: str) -> str:
    """搜索并推荐指定类型的经典电影。"""
    return f"【工具返回】推荐以下经典{genre}电影：《星际穿越》、《沙丘》、《银翼杀手 2049》。"


@tool
def search_papers(query: str) -> str:
    """在学术文献库中检索学术论文。"""
    return f"【工具返回】为您检索到关于 '{query}' 的最新文献：\n1. 《Deep Graph Networks: A Survey》\n2. 《Agentic RAG with Memory Flow》\n3. 《Hierarchical LangGraph Workflows for Enterprises》"


@tool
def write_code(language: str, requirement: str) -> str:
    """根据需求编写指定编程语言的代码。"""
    lang = language.lower().strip()
    if "python" in lang or "py" in lang:
        code = (
            "```python\n"
            "def binary_search(arr, target):\n"
            "    # Requirement: " + requirement + "\n"
            "    low, high = 0, len(arr) - 1\n"
            "    while low <= high:\n"
            "        mid = (low + high) // 2\n"
            "        if arr[mid] == target:\n"
            "            return mid\n"
            "        elif arr[mid] < target:\n"
            "            low = mid + 1\n"
            "        else:\n"
            "            high = mid - 1\n"
            "    return -1\n"
            "```"
        )
    elif "java" in lang or "jvm" in lang:
        code = (
            "```java\n"
            "public class Solution {\n"
            "    // Requirement: " + requirement + "\n"
            "    public static void main(String[] args) {\n"
            "        System.out.println(\"Hello Code Agent!\");\n"
            "    }\n"
            "}\n"
            "```"
        )
    else:
        code = (
            "```javascript\n"
            "// Requirement: " + requirement + "\n"
            "function solve() {\n"
            "    console.log('Code generated by Code Agent');\n"
            "}\n"
            "```"
        )
    return f"【工具返回】已为您生成相关的 {language} 代码：\n\n{code}"


# ============================================================
# 2. HITL 工具：带人工审批中断
# ============================================================
@tool
def send_email_hitl(to_address: str, subject: str, body: str) -> str:
    """给指定的电子邮箱发送邮件——此操作需要人工审批。"""
    response = interrupt({
        "type": "tool_approval",
        "tool_name": "send_email",
        "args": {
            "to_address": to_address,
            "subject": subject,
            "body": body,
        },
        "message": "请审核此邮件。您可以选择批准、拒绝或进行编辑。",
        "severity": "medium",
    })

    if response.get("action") == "approve":
        return f"【工具返回】已成功向 <{to_address}> 发送主题为《{subject}》的邮件，内容大小：{len(body)} 字节。"
    elif response.get("action") == "reject":
        return "【工具返回】邮件发送已被用户取消。"
    elif response.get("action") == "edit":
        to_address = response.get("to_address", to_address)
        subject = response.get("subject", subject)
        body = response.get("body", body)
        return (
            f"【工具返回】已使用编辑后的内容发送邮件：\n"
            f"收件人: {to_address}\n"
            f"主题: {subject}\n"
            f"正文: {body}"
        )
    return "【工具返回】未知的响应类型，操作已取消。"


@tool
def delete_database(database_name: str) -> str:
    """删除数据库。此操作极其危险！"""
    response = interrupt({
        "type": "tool_approval",
        "tool_name": "delete_database",
        "args": {"database_name": database_name},
        "message": "你绝对确定要删除这个数据库吗？此操作不可撤销！",
        "severity": "high",
    })
    if response.get("action") == "approve":
        return f"【工具返回】数据库 '{database_name}' 已被删除（模拟操作）。"
    else:
        return "【工具返回】数据库删除操作已被取消。"


@tool
def make_purchase(item_name: str, amount: float) -> str:
    """进行采购。超过 $1000 的采购需要人工审批。"""
    if amount > 1000:
        response = interrupt({
            "type": "tool_approval",
            "tool_name": "make_purchase",
            "args": {"item_name": item_name, "amount": amount},
            "message": f"采购金额 ${amount:.2f} 超过 $1000 阈值，需要人工审批。",
            "severity": "high",
            "reason": "amount_exceeds_threshold",
        })
        if response.get("action") == "approve":
            return f"【工具返回】已批准采购 {item_name}，金额 ${amount:.2f}。"
        elif response.get("action") == "reject":
            return f"【工具返回】采购 {item_name}（${amount:.2f}）已被拒绝。"
        else:
            return "【工具返回】采购操作已取消。"
    else:
        return f"【工具返回】已自动完成采购 {item_name}，金额 ${amount:.2f}。"


# ============================================================
# 3. 工具注册表
# ============================================================
regular_tools = [get_weather, search_movies, search_papers, write_code]
tools_by_name = {tool.name: tool for tool in regular_tools}

hitl_tools = [send_email_hitl, delete_database, make_purchase]
hitl_tools_by_name = {tool.name: tool for tool in hitl_tools}

all_tools = regular_tools + hitl_tools


# ============================================================
# 4. 安全中间件（AgentMiddleware 模式）
# ============================================================
class SafetyMiddleware:
    """安全中间件：在模型输出后检测危险工具调用并记录日志。"""
    name = "safety_checker"
    dangerous_keywords = ["delete", "destroy", "drop", "wipe"]

    def after_model(self, state: dict[str, Any], runtime=None) -> dict[str, Any] | None:
        messages = state.get("messages", [])
        if not messages:
            return None
        last_message = messages[-1]
        tool_calls = getattr(last_message, "tool_calls", None) or []
        for tc in tool_calls:
            tool_name = tc.get("name", "").lower()
            for kw in self.dangerous_keywords:
                if kw in tool_name:
                    print(f"   [SAFETY] Dangerous operation detected!")
                    print(f"   Tool: {tc.get('name')}")
                    print(f"   Args: {tc.get('args')}")
        return None


class RequestLoggerMiddleware:
    """请求日志中间件：在模型调用前后打印调试信息。"""
    name = "request_logger"

    def before_model(self, state: dict[str, Any], runtime=None) -> dict[str, Any] | None:
        message_count = len(state.get("messages", []))
        print(f"[BEFORE MODEL] Processing {message_count} messages")
        return None

    def after_model(self, state: dict[str, Any], runtime=None) -> dict[str, Any] | None:
        messages = state.get("messages", [])
        if messages:
            last = messages[-1]
            tool_calls = getattr(last, "tool_calls", None) or []
            if tool_calls:
                print(f"[AFTER MODEL] Model requested {len(tool_calls)} tool call(s)")
            else:
                print(f"[AFTER MODEL] Model provided final response")
        return None
